/* SPDX-License-Identifier: Apache-2.0 */
rootProject.name = "atlan-java"
include("sdk")
include("generate")
include("integration-tests")
include("mocks")
include("package-toolkit:config")
include("package-toolkit:events")
include("package-toolkit:runtime")
include("package-toolkit:testing")
include("samples:packages:admin-export")
include("samples:packages:api-token-connection-admin")
include("samples:packages:asset-export-basic")
include("samples:packages:asset-import")
include("samples:packages:duplicate-detector")
include("samples:packages:metadata-impact-report")
include("samples:packages:openapi-spec-loader")
include("samples:packages:owner-propagator")
include("samples:packages:relational-assets-builder")
include("samples:pipelines:asset-scorer")
include("samples:pipelines:verification-enforcer")
include("samples:standalone:sdk-extension")
include("samples:packages:adoption-export")
