/* SPDX-License-Identifier: Apache-2.0 */
rootProject.name = "atlan-java"
include("sdk")
include("generate")
include("integration-tests")
include("mocks")
include("package-toolkit:config")
include("package-toolkit:runtime")
include("package-toolkit:testing")
include("samples:packages:admin-export")
include("samples:packages:api-token-connection-admin")
include("samples:packages:asset-export-basic")
include("samples:packages:asset-import")
include("samples:packages:cube-assets-builder")
include("samples:packages:custom-metadata-extender")
include("samples:packages:duplicate-detector")
include("samples:packages:lake-formation-tag-sync")
include("samples:packages:metadata-impact-report")
include("samples:packages:openapi-spec-loader")
include("samples:packages:owner-propagator")
include("samples:packages:relational-assets-builder")
include("samples:packages:scim-group-cleanup")
include("samples:packages:tests-cleanup")
include("samples:standalone:sdk-extension")
include("samples:packages:adoption-export")
include("samples:packages:enrichment-migrator")
include("samples:packages:lineage-builder")
