/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright 2022 Atlan Pte. Ltd. */
package com.atlan.model.assets;

import static org.testng.Assert.*;

import com.atlan.model.enums.*;
import com.atlan.model.structs.*;
import com.atlan.serde.Serde;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.*;
import org.testng.annotations.Test;

@SuppressWarnings("deprecation")
public class ColumnTest {

    private static final Column full = Column.builder()
            .guid("guid")
            .displayText("displayText")
            .status(AtlanStatus.ACTIVE)
            .createdBy("createdBy")
            .updatedBy("updatedBy")
            .createTime(123456789L)
            .updateTime(123456789L)
            .isIncomplete(false)
            .deleteHandler("SOFT")
            .meaningNames(Set.of("meaningName1", "meaningName2"))
            .meanings(Set.of(
                    Meaning.builder()
                            .termGuid("termGuid1")
                            .relationGuid("relationGuid1")
                            .displayText("displayText1")
                            .confidence(100)
                            .build(),
                    Meaning.builder()
                            .termGuid("termGuid2")
                            .relationGuid("relationGuid2")
                            .displayText("displayText2")
                            .confidence(100)
                            .build()))
            .qualifiedName("qualifiedName")
            .name("String0")
            .displayName("String0")
            .description("String0")
            .userDescription("String0")
            .tenantId("String0")
            .certificateStatus(CertificateStatus.DEPRECATED)
            .certificateStatusMessage("String0")
            .certificateUpdatedBy("String0")
            .certificateUpdatedAt(123456789L)
            .announcementTitle("String0")
            .announcementMessage("String0")
            .announcementType(AtlanAnnouncementType.INFORMATION)
            .announcementUpdatedAt(123456789L)
            .announcementUpdatedBy("String0")
            .ownerUser("String0")
            .ownerUser("String1")
            .ownerGroup("String0")
            .ownerGroup("String1")
            .adminUser("String0")
            .adminUser("String1")
            .adminGroup("String0")
            .adminGroup("String1")
            .viewerUser("String0")
            .viewerUser("String1")
            .viewerGroup("String0")
            .viewerGroup("String1")
            .connectorType(AtlanConnectorType.SNOWFLAKE)
            .connectionName("String0")
            .connectionQualifiedName("String0")
            .hasLineage(true)
            .isDiscoverable(true)
            .isEditable(true)
            .subType("String0")
            .viewScore(123.456)
            .popularityScore(123.456)
            .sourceOwners("String0")
            .sourceCreatedBy("String0")
            .sourceCreatedAt(123456789L)
            .sourceUpdatedAt(123456789L)
            .sourceUpdatedBy("String0")
            .sourceURL("String0")
            .sourceEmbedURL("String0")
            .lastSyncWorkflowName("String0")
            .lastSyncRunAt(123456789L)
            .lastSyncRun("String0")
            .adminRole("String0")
            .adminRole("String1")
            .sourceReadCount(123456789L)
            .sourceReadUserCount(123456789L)
            .sourceLastReadAt(123456789L)
            .lastRowChangedAt(123456789L)
            .sourceTotalCost(123.456)
            .sourceCostUnit(SourceCostUnitType.CREDITS)
            .sourceReadRecentUser("String0")
            .sourceReadRecentUser("String1")
            .sourceReadRecentUserRecord(PopularityInsights.builder()
                    .recordUser("String0")
                    .recordQuery("String0")
                    .recordQueryDuration(123456789L)
                    .recordQueryCount(123456789L)
                    .recordTotalUserCount(123456789L)
                    .recordComputeCost(123.456)
                    .recordMaxComputeCost(123.456)
                    .recordComputeCostUnit(SourceCostUnitType.CREDITS)
                    .recordLastTimestamp(123456789L)
                    .recordWarehouse("String0")
                    .build())
            .sourceReadRecentUserRecord(PopularityInsights.builder()
                    .recordUser("String1")
                    .recordQuery("String1")
                    .recordQueryDuration(987654321L)
                    .recordQueryCount(987654321L)
                    .recordTotalUserCount(987654321L)
                    .recordComputeCost(654.321)
                    .recordMaxComputeCost(654.321)
                    .recordComputeCostUnit(SourceCostUnitType.BYTES)
                    .recordLastTimestamp(987654321L)
                    .recordWarehouse("String1")
                    .build())
            .sourceReadTopUser("String0")
            .sourceReadTopUser("String1")
            .sourceReadTopUserRecord(PopularityInsights.builder()
                    .recordUser("String0")
                    .recordQuery("String0")
                    .recordQueryDuration(123456789L)
                    .recordQueryCount(123456789L)
                    .recordTotalUserCount(123456789L)
                    .recordComputeCost(123.456)
                    .recordMaxComputeCost(123.456)
                    .recordComputeCostUnit(SourceCostUnitType.CREDITS)
                    .recordLastTimestamp(123456789L)
                    .recordWarehouse("String0")
                    .build())
            .sourceReadTopUserRecord(PopularityInsights.builder()
                    .recordUser("String1")
                    .recordQuery("String1")
                    .recordQueryDuration(987654321L)
                    .recordQueryCount(987654321L)
                    .recordTotalUserCount(987654321L)
                    .recordComputeCost(654.321)
                    .recordMaxComputeCost(654.321)
                    .recordComputeCostUnit(SourceCostUnitType.BYTES)
                    .recordLastTimestamp(987654321L)
                    .recordWarehouse("String1")
                    .build())
            .sourceReadPopularQueryRecord(PopularityInsights.builder()
                    .recordUser("String0")
                    .recordQuery("String0")
                    .recordQueryDuration(123456789L)
                    .recordQueryCount(123456789L)
                    .recordTotalUserCount(123456789L)
                    .recordComputeCost(123.456)
                    .recordMaxComputeCost(123.456)
                    .recordComputeCostUnit(SourceCostUnitType.CREDITS)
                    .recordLastTimestamp(123456789L)
                    .recordWarehouse("String0")
                    .build())
            .sourceReadPopularQueryRecord(PopularityInsights.builder()
                    .recordUser("String1")
                    .recordQuery("String1")
                    .recordQueryDuration(987654321L)
                    .recordQueryCount(987654321L)
                    .recordTotalUserCount(987654321L)
                    .recordComputeCost(654.321)
                    .recordMaxComputeCost(654.321)
                    .recordComputeCostUnit(SourceCostUnitType.BYTES)
                    .recordLastTimestamp(987654321L)
                    .recordWarehouse("String1")
                    .build())
            .sourceReadExpensiveQueryRecord(PopularityInsights.builder()
                    .recordUser("String0")
                    .recordQuery("String0")
                    .recordQueryDuration(123456789L)
                    .recordQueryCount(123456789L)
                    .recordTotalUserCount(123456789L)
                    .recordComputeCost(123.456)
                    .recordMaxComputeCost(123.456)
                    .recordComputeCostUnit(SourceCostUnitType.CREDITS)
                    .recordLastTimestamp(123456789L)
                    .recordWarehouse("String0")
                    .build())
            .sourceReadExpensiveQueryRecord(PopularityInsights.builder()
                    .recordUser("String1")
                    .recordQuery("String1")
                    .recordQueryDuration(987654321L)
                    .recordQueryCount(987654321L)
                    .recordTotalUserCount(987654321L)
                    .recordComputeCost(654.321)
                    .recordMaxComputeCost(654.321)
                    .recordComputeCostUnit(SourceCostUnitType.BYTES)
                    .recordLastTimestamp(987654321L)
                    .recordWarehouse("String1")
                    .build())
            .sourceReadSlowQueryRecord(PopularityInsights.builder()
                    .recordUser("String0")
                    .recordQuery("String0")
                    .recordQueryDuration(123456789L)
                    .recordQueryCount(123456789L)
                    .recordTotalUserCount(123456789L)
                    .recordComputeCost(123.456)
                    .recordMaxComputeCost(123.456)
                    .recordComputeCostUnit(SourceCostUnitType.CREDITS)
                    .recordLastTimestamp(123456789L)
                    .recordWarehouse("String0")
                    .build())
            .sourceReadSlowQueryRecord(PopularityInsights.builder()
                    .recordUser("String1")
                    .recordQuery("String1")
                    .recordQueryDuration(987654321L)
                    .recordQueryCount(987654321L)
                    .recordTotalUserCount(987654321L)
                    .recordComputeCost(654.321)
                    .recordMaxComputeCost(654.321)
                    .recordComputeCostUnit(SourceCostUnitType.BYTES)
                    .recordLastTimestamp(987654321L)
                    .recordWarehouse("String1")
                    .build())
            .sourceQueryComputeCost("String0")
            .sourceQueryComputeCost("String1")
            .sourceQueryComputeCostRecord(PopularityInsights.builder()
                    .recordUser("String0")
                    .recordQuery("String0")
                    .recordQueryDuration(123456789L)
                    .recordQueryCount(123456789L)
                    .recordTotalUserCount(123456789L)
                    .recordComputeCost(123.456)
                    .recordMaxComputeCost(123.456)
                    .recordComputeCostUnit(SourceCostUnitType.CREDITS)
                    .recordLastTimestamp(123456789L)
                    .recordWarehouse("String0")
                    .build())
            .sourceQueryComputeCostRecord(PopularityInsights.builder()
                    .recordUser("String1")
                    .recordQuery("String1")
                    .recordQueryDuration(987654321L)
                    .recordQueryCount(987654321L)
                    .recordTotalUserCount(987654321L)
                    .recordComputeCost(654.321)
                    .recordMaxComputeCost(654.321)
                    .recordComputeCostUnit(SourceCostUnitType.BYTES)
                    .recordLastTimestamp(987654321L)
                    .recordWarehouse("String1")
                    .build())
            .dbtQualifiedName("String0")
            .assetDbtAlias("String0")
            .assetDbtMeta("String0")
            .assetDbtUniqueId("String0")
            .assetDbtAccountName("String0")
            .assetDbtProjectName("String0")
            .assetDbtPackageName("String0")
            .assetDbtJobName("String0")
            .assetDbtJobSchedule("String0")
            .assetDbtJobStatus("String0")
            .assetDbtJobScheduleCronHumanized("String0")
            .assetDbtJobLastRun(123456789L)
            .assetDbtJobLastRunUrl("String0")
            .assetDbtJobLastRunCreatedAt(123456789L)
            .assetDbtJobLastRunUpdatedAt(123456789L)
            .assetDbtJobLastRunDequedAt(123456789L)
            .assetDbtJobLastRunStartedAt(123456789L)
            .assetDbtJobLastRunTotalDuration("String0")
            .assetDbtJobLastRunTotalDurationHumanized("String0")
            .assetDbtJobLastRunQueuedDuration("String0")
            .assetDbtJobLastRunQueuedDurationHumanized("String0")
            .assetDbtJobLastRunRunDuration("String0")
            .assetDbtJobLastRunRunDurationHumanized("String0")
            .assetDbtJobLastRunGitBranch("String0")
            .assetDbtJobLastRunGitSha("String0")
            .assetDbtJobLastRunStatusMessage("String0")
            .assetDbtJobLastRunOwnerThreadId("String0")
            .assetDbtJobLastRunExecutedByThreadId("String0")
            .assetDbtJobLastRunArtifactsSaved(true)
            .assetDbtJobLastRunArtifactS3Path("String0")
            .assetDbtJobLastRunHasDocsGenerated(true)
            .assetDbtJobLastRunHasSourcesGenerated(true)
            .assetDbtJobLastRunNotificationsSent(true)
            .assetDbtJobNextRun(123456789L)
            .assetDbtJobNextRunHumanized("String0")
            .assetDbtEnvironmentName("String0")
            .assetDbtEnvironmentDbtVersion("String0")
            .assetDbtTag("String0")
            .assetDbtTag("String1")
            .assetDbtSemanticLayerProxyUrl("String0")
            .assetDbtSourceFreshnessCriteria("String0")
            .sampleDataUrl("String0")
            .assetTag("String0")
            .assetTag("String1")
            .link(Link.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .link(Link.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .metric(DbtMetric.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .metric(DbtMetric.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .readme(Readme.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .assignedTerm(GlossaryTerm.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .assignedTerm(GlossaryTerm.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .inputToProcess(LineageProcess.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .inputToProcess(LineageProcess.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .outputFromProcess(LineageProcess.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .outputFromProcess(LineageProcess.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .queryCount(123456789L)
            .queryUserCount(123456789L)
            .putQueryUserMap("key1", 123456L)
            .putQueryUserMap("key2", 654321L)
            .queryCountUpdatedAt(123456789L)
            .databaseName("String0")
            .databaseQualifiedName("String0")
            .schemaName("String0")
            .schemaQualifiedName("String0")
            .tableName("String0")
            .tableQualifiedName("String0")
            .viewName("String0")
            .viewQualifiedName("String0")
            .isProfiled(true)
            .lastProfiledAt(123456789L)
            .dbtModel(DbtModel.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .dbtModel(DbtModel.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .dbtSource(DbtSource.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .dbtSource(DbtSource.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .sqlDbtModel(DbtModel.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .sqlDbtModel(DbtModel.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .sqlDBTSource(DbtSource.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .sqlDBTSource(DbtSource.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .dataType("String0")
            .subDataType("String0")
            .order(123)
            .isPartition(true)
            .partitionOrder(123)
            .isClustered(true)
            .isPrimary(true)
            .isForeign(true)
            .isIndexed(true)
            .isSort(true)
            .isDist(true)
            .isPinned(true)
            .pinnedBy("String0")
            .pinnedAt(123456789L)
            .precision(123)
            .defaultValue("String0")
            .isNullable(true)
            .numericScale(123.456)
            .maxLength(123456789L)
            .validation("key1", "value1")
            .validation("key2", "value2")
            .columnDistinctValuesCount(123)
            .columnDistinctValuesCountLong(123456789L)
            .addColumnHistogram(Histogram.builder()
                    .boundaries(List.of(123.456, 654.321))
                    .frequencies(List.of(123.456, 654.321))
                    .build())
            .addColumnHistogram(Histogram.builder()
                    .boundaries(List.of(123.456, 654.321))
                    .frequencies(List.of(123.456, 654.321))
                    .build())
            .columnMax(123.456)
            .columnMin(123.456)
            .columnMean(123.456)
            .columnSum(123.456)
            .columnMedian(123.456)
            .columnStandardDeviation(123.456)
            .columnUniqueValuesCount(123)
            .columnUniqueValuesCountLong(123456789L)
            .columnAverage(123.456)
            .columnAverageLength(123.456)
            .columnDuplicateValuesCount(123)
            .columnDuplicateValuesCountLong(123456789L)
            .columnMaximumStringLength(123)
            .addColumnMax("String0")
            .addColumnMax("String1")
            .columnMinimumStringLength(123)
            .addColumnMin("String0")
            .addColumnMin("String1")
            .columnMissingValuesCount(123)
            .columnMissingValuesCountLong(123456789L)
            .columnMissingValuesPercentage(123.456)
            .columnUniquenessPercentage(123.456)
            .columnVariance(123.456)
            .columnTopValue(ColumnValueFrequencyMap.builder()
                    .columnValue("String0")
                    .columnValueFrequency(123456789L)
                    .build())
            .columnTopValue(ColumnValueFrequencyMap.builder()
                    .columnValue("String1")
                    .columnValueFrequency(987654321L)
                    .build())
            .materializedView(MaterializedView.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .query(AtlanQuery.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .query(AtlanQuery.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .metricTimestamp(DbtMetric.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .metricTimestamp(DbtMetric.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .addForeignKeyTo(Column.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .addForeignKeyTo(Column.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .foreignKeyFrom(Column.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .dbtMetric(DbtMetric.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .dbtMetric(DbtMetric.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .view(View.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .tablePartition(TablePartition.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .dataQualityMetricDimension(DbtMetric.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .dataQualityMetricDimension(DbtMetric.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .dbtModelColumn(DbtModelColumn.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .dbtModelColumn(DbtModelColumn.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .table(Table.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .columnDbtModelColumn(DbtModelColumn.refByGuid("705d96f4-bdb6-4792-8dfe-8dc4ca3d2c23"))
            .columnDbtModelColumn(DbtModelColumn.refByQualifiedName("default/snowflake/1234567890/test/qualifiedName"))
            .build();

    private static final int hash = full.hashCode();
    private static Column frodo;
    private static String serialized;

    @Test(groups = {"Column.builderEquivalency"})
    void builderEquivalency() {
        assertEquals(full.toBuilder().build(), full);
    }

    @Test(
            groups = {"Column.serialize"},
            dependsOnGroups = {"Column.builderEquivalency"})
    void serialization() {
        assertNotNull(full);
        serialized = full.toJson();
        assertNotNull(serialized);
        assertEquals(full.hashCode(), hash, "Serialization mutated the original value,");
    }

    @Test(
            groups = {"Column.deserialize"},
            dependsOnGroups = {"Column.serialize"})
    void deserialization() throws JsonProcessingException {
        assertNotNull(serialized);
        frodo = Serde.mapper.readValue(serialized, Column.class);
        assertNotNull(frodo);
    }

    @Test(
            groups = {"Column.equivalency"},
            dependsOnGroups = {"Column.serialize", "Column.deserialize"})
    void serializedEquivalency() {
        assertNotNull(serialized);
        assertNotNull(frodo);
        String backAgain = frodo.toJson();
        assertEquals(backAgain, serialized, "Serialization is not equivalent after serde loop,");
    }

    @Test(
            groups = {"Column.equivalency"},
            dependsOnGroups = {"Column.serialize", "Column.deserialize"})
    void deserializedEquivalency() {
        assertNotNull(full);
        assertNotNull(frodo);
        assertEquals(frodo, full, "Deserialization is not equivalent after serde loop,");
    }
}
