[versions]
jackson = "2.17.2"
slf4j = "2.0.16"
elasticsearch = "8.15.1"
freemarker = "2.3.33"
classgraph = "4.8.176"
testng = "7.10.2"
log4j = "2.24.0"
wiremock = "3.9.1"
jnanoid = "2.0.0"
numaflow = "0.8.0"
awssdk = "2.28.5"
gcs = "26.47.0"
system-stubs = "2.1.6"
fastcsv = "3.3.0"
poi = "5.3.0"
parsson = "1.1.7"
simplejavamail = "8.11.3"
swagger = "2.1.22"
jsonpath = "2.9.0"
commons-compress = "1.27.1"
sqlite = "3.46.1.0"
jakarta-mail = "2.1.3"
angus-mail = "2.0.3"
pkl = "0.26.3"
adls = "12.21.0"
azure = "1.13.3"
guava = "33.3.0-jre"
openlineage = "1.22.0"

[libraries]
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
elasticsearch-java = { module = "co.elastic.clients:elasticsearch-java", version.ref = "elasticsearch" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
testng = { module = "org.testng:testng", version.ref = "testng" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2 = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
jnanoid = { module = "com.aventrix.jnanoid:jnanoid", version.ref = "jnanoid" }
numaflow-java = { module = "io.numaproj.numaflow:numaflow-java", version.ref = "numaflow" }
awssdk-s3 = { module = "software.amazon.awssdk:s3", version.ref = "awssdk" }
gcs-bom = { module = "com.google.cloud:libraries-bom", version.ref = "gcs" }
gcs = { module = "com.google.cloud:google-cloud-storage" }
gcs-control = { module = "com.google.cloud:google-cloud-storage-control" }
adls = { module = "com.azure:azure-storage-file-datalake", version.ref = "adls" }
azure-identity = { module = "com.azure:azure-identity", version.ref = "azure" }
system-stubs = { module = "uk.org.webcompere:system-stubs-testng", version.ref = "system-stubs" }
fastcsv = { module = "de.siegmar:fastcsv", version.ref = "fastcsv" }
apache-poi = { module = "org.apache.poi:poi", version.ref = "poi" }
apache-poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
parsson = { module = "org.eclipse.parsson:parsson", version.ref = "parsson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
simple-java-mail = { module = "org.simplejavamail:simple-java-mail", version.ref = "simplejavamail" }
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version.ref = "swagger" }
json-path = { module = "com.jayway.jsonpath:json-path", version.ref = "jsonpath" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
jakarta-mail = { module = "com.sun.mail:jakarta.mail", version.ref = "jakarta-mail" }
angus-mail = { module = "org.eclipse.angus:angus-mail", version.ref = "angus-mail" }
pkl-config = { module = "org.pkl-lang:pkl-config-kotlin", version.ref = "pkl" }
pkl-codegen = { module = "org.pkl-lang:pkl-codegen-kotlin", version.ref = "pkl" }
openlineage = { module = "io.openlineage:openlineage-java", version.ref = "openlineage" }

[bundles]
java-test = [ "jnanoid", "testng", "wiremock" ]
log4j = [ "log4j-core", "log4j-slf4j2" ]
poi = [ "apache-poi", "apache-poi-ooxml" ]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
git-publish = { id = "org.ajoberstar.git-publish", version = "4.2.2" }
pkl = { id = "org.pkl-lang", version = "0.26.3" }
