[versions]
jackson = "2.16.1"
slf4j = "2.0.12"
elasticsearch = "8.12.2"
freemarker = "2.3.32"
classgraph = "4.8.165"
testng = "7.8.0"
log4j = "2.23.0"
wiremock = "3.4.2"
jnanoid = "2.0.0"
numaflow = "0.6.0"
awssdk = "2.24.11"
system-stubs = "2.1.6"
fastcsv = "3.0.0"
poi = "5.2.5"
parsson = "1.1.5"
simplejavamail = "8.6.3"
swagger = "2.1.20"
jsonpath = "2.9.0"
commons-compress = "1.26.0"
sqlite = "3.45.1.0"

[libraries]
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-yaml = {module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
elasticsearch-java = { module = "co.elastic.clients:elasticsearch-java", version.ref = "elasticsearch" }
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
testng = { module = "org.testng:testng", version.ref = "testng" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2 = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
jnanoid = { module = "com.aventrix.jnanoid:jnanoid", version.ref = "jnanoid" }
numaflow-java = { module = "io.numaproj.numaflow:numaflow-java", version.ref = "numaflow" }
awssdk-s3 = { module = "software.amazon.awssdk:s3", version.ref = "awssdk" }
system-stubs = { module = "uk.org.webcompere:system-stubs-testng", version.ref = "system-stubs" }
fastcsv = { module = "de.siegmar:fastcsv", version.ref = "fastcsv" }
apache-poi = { module = "org.apache.poi:poi", version.ref = "poi" }
apache-poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
parsson = { module = "org.eclipse.parsson:parsson", version.ref = "parsson" }
simple-java-mail = { module = "org.simplejavamail:simple-java-mail", version.ref = "simplejavamail" }
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version.ref = "swagger" }
json-path = { module = "com.jayway.jsonpath:json-path", version.ref = "jsonpath" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }

[bundles]
java-test = [ "jnanoid", "testng", "wiremock" ]
log4j = [ "log4j-core", "log4j-slf4j2" ]
poi = [ "apache-poi", "apache-poi-ooxml" ]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }
git-publish = { id = "org.ajoberstar.git-publish", version = "3.0.1" }
