# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 Atlan Pte. Ltd.
name: "Custom package container"
permissions:
  contents: read
  packages: write

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      version:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: ''

jobs:
  custom-package-container:
    runs-on: ubuntu-latest
    name: "${{inputs.package_name}} container"
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6.0.0
        with:
          ref: ${{ inputs.branch != '' && inputs.branch || github.ref }}
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435  # v3.11.1
      - name: Log in to container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef  # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create assembly area
        run: |
          mkdir -p ./containers/custom-package/assembly
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53  # v6.0.0
        with:
          name: "${{inputs.package_name}}-amd64"
          path: ./containers/custom-package/amd64/assembly
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53  # v6.0.0
        with:
          name: "${{inputs.package_name}}-arm64"
          path: ./containers/custom-package/arm64/assembly
      - name: Determine image tags and version
        id: tags
        run: |
          if [ -n "${{ inputs.branch }}" ]; then
            # For manual runs with branch specified, use version and branch name (sanitized)
            BRANCH_NAME=$(echo "${{ inputs.branch }}" | sed 's/[^a-zA-Z0-9._-]/-/g')
            echo "tags=ghcr.io/atlanhq/csa-${{inputs.package_name}}:${{inputs.version}}-${BRANCH_NAME}" >> $GITHUB_OUTPUT
            echo "build_version=${{inputs.version}}-${BRANCH_NAME}" >> $GITHUB_OUTPUT
          else
            # For main branch pushes, use version and latest
            echo "tags=ghcr.io/atlanhq/csa-${{inputs.package_name}}:${{inputs.version}},ghcr.io/atlanhq/csa-${{inputs.package_name}}:latest" >> $GITHUB_OUTPUT
            echo "build_version=${{inputs.version}}" >> $GITHUB_OUTPUT
          fi
      - name: Build and publish container image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83  # v6.18.0
        with:
          build-args: |
            VERSION=${{ steps.tags.outputs.build_version }}
            PKG_NAME=${{inputs.package_name}}
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          context: ./containers/custom-package
          platforms: linux/amd64,linux/arm64
